# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blueking.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'blueking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62lueking.proto\x12\x08\x62lueking\".\n\tChatEvent\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1d\n\x0c\x43hatResponse\x12\r\n\x05reply\x18\x01 \x01(\t\")\n\x16SendChatMessageRequest\x12\x0f\n\x07payload\x18\x01 \x01(\t\"\xa1\x01\n\x17SendChatMessageResponse\x12\x38\n\x06status\x18\x01 \x01(\x0e\x32(.blueking.SendChatMessageResponse.Status\x12\x15\n\rerror_message\x18\x02 \x01(\t\"5\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\x12\n\x0eNO_CHAT_CLIENT\x10\x01\x12\x0f\n\x0bSEND_FAILED\x10\x02\x32<\n\x05\x42rain\x12\x33\n\x04\x43hat\x12\x13.blueking.ChatEvent\x1a\x16.blueking.ChatResponse2a\n\x07Gestalt\x12V\n\x0fSendChatMessage\x12 .blueking.SendChatMessageRequest\x1a!.blueking.SendChatMessageResponse2\t\n\x07Storageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blueking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATEVENT']._serialized_start=28
  _globals['_CHATEVENT']._serialized_end=74
  _globals['_CHATRESPONSE']._serialized_start=76
  _globals['_CHATRESPONSE']._serialized_end=105
  _globals['_SENDCHATMESSAGEREQUEST']._serialized_start=107
  _globals['_SENDCHATMESSAGEREQUEST']._serialized_end=148
  _globals['_SENDCHATMESSAGERESPONSE']._serialized_start=151
  _globals['_SENDCHATMESSAGERESPONSE']._serialized_end=312
  _globals['_SENDCHATMESSAGERESPONSE_STATUS']._serialized_start=259
  _globals['_SENDCHATMESSAGERESPONSE_STATUS']._serialized_end=312
  _globals['_BRAIN']._serialized_start=314
  _globals['_BRAIN']._serialized_end=374
  _globals['_GESTALT']._serialized_start=376
  _globals['_GESTALT']._serialized_end=473
  _globals['_STORAGE']._serialized_start=475
  _globals['_STORAGE']._serialized_end=484
# @@protoc_insertion_point(module_scope)
